/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.FinalProject;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.io.File;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.TransferHandler;
import my.FinalProject.FileDrop;
import my.FinalProject.FileDropFrame;



/**
 *
 * @author Danish
 */
public class FinalProjectUI extends javax.swing.JFrame {

    /**
     * Creates new form FinalProjectUI
     */
    
    private String month;
    private int day;
    private int year;
    private String time;
    private FileDropFrame fileDropFrame = new FileDropFrame();
    private Ascadac parser = new Ascadac();
    private message[] messageArray;
    private String[] monthArray = {"January", "Febraury", "March", "April", "May", "June", "July", 
        "August", "September", "October", "November", "December", ""}; 
    
    
    
    public FinalProjectUI() {
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
        fileDropFrame.setAlwaysOnTop(true);
        fileDropFrame.setVisible(true);
        
        
        
        textArea1.setEditable(false);
        textArea1.setLineWrap(true);
        textArea1.setWrapStyleWord(true);
        
        
        
        
      
       /*
       jPanel1.setDropTarget(new DropTarget() {
        public synchronized void drop(DropTargetDropEvent dropEvent) {
            try {
                dropEvent.acceptDrop(DnDConstants.ACTION_COPY);
                List<File> droppedFiles = (List<File>) dropEvent.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                for (File file : droppedFiles) {
                    textArea1.append(file.getAbsolutePath());
                    filePath = file.getAbsolutePath();
                    textArea1.append(filePath);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    });
        
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        MessagePanel = new javax.swing.JPanel();
        MOperatePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        monthChoiceBox = new javax.swing.JComboBox();
        searchButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        senderTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dayTxtField = new javax.swing.JTextField();
        yearTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        wordPhraseTxtField = new javax.swing.JTextField();
        MTextArea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MessagePanel.setBackground(new java.awt.Color(131, 206, 255));

        MOperatePanel.setBackground(new java.awt.Color(98, 233, 247));
        MOperatePanel.setOpaque(false);

        jLabel1.setText("Search for messages by:");

        monthChoiceBox.setBackground(new java.awt.Color(78, 170, 245));
        monthChoiceBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", "None" }));

        searchButton.setBackground(new java.awt.Color(153, 153, 153));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(153, 153, 153));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        senderTxtField.setBackground(new java.awt.Color(230, 250, 255));
        senderTxtField.setToolTipText("Search by sender");

        jLabel2.setText("Date:");

        jLabel3.setText("Month");

        jLabel4.setText("Day");

        dayTxtField.setBackground(new java.awt.Color(230, 250, 255));

        yearTxtField.setBackground(new java.awt.Color(230, 250, 255));
        yearTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Year");

        jLabel6.setText("Sender:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 255));
        jLabel9.setText("Messages");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Choose File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Keyword:/Phrase:");

        wordPhraseTxtField.setBackground(new java.awt.Color(230, 250, 255));
        wordPhraseTxtField.setToolTipText("Search by sender");

        javax.swing.GroupLayout MOperatePanelLayout = new javax.swing.GroupLayout(MOperatePanel);
        MOperatePanel.setLayout(MOperatePanelLayout);
        MOperatePanelLayout.setHorizontalGroup(
            MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MOperatePanelLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MOperatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MOperatePanelLayout.createSequentialGroup()
                        .addGroup(MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(senderTxtField)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MOperatePanelLayout.createSequentialGroup()
                                .addGroup(MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MOperatePanelLayout.createSequentialGroup()
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(77, 77, 77))
                    .addGroup(MOperatePanelLayout.createSequentialGroup()
                        .addGroup(MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(MOperatePanelLayout.createSequentialGroup()
                                .addGroup(MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(MOperatePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(62, 62, 62))
                                    .addComponent(monthChoiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(dayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(yearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(wordPhraseTxtField)
                    .addGroup(MOperatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12))))
        );
        MOperatePanelLayout.setVerticalGroup(
            MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MOperatePanelLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(senderTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthChoiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordPhraseTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(MOperatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MTextArea.setBackground(new java.awt.Color(98, 233, 247));
        MTextArea.setOpaque(false);

        textArea1.setBackground(new java.awt.Color(230, 250, 255));
        textArea1.setColumns(20);
        textArea1.setRows(5);
        textArea1.setMargin(new java.awt.Insets(100, 100, 100, 100));
        jScrollPane1.setViewportView(textArea1);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MIconV2Ex.png"))); // NOI18N

        javax.swing.GroupLayout MTextAreaLayout = new javax.swing.GroupLayout(MTextArea);
        MTextArea.setLayout(MTextAreaLayout);
        MTextAreaLayout.setHorizontalGroup(
            MTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MTextAreaLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MTextAreaLayout.createSequentialGroup()
                .addGap(0, 338, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(324, 324, 324))
        );
        MTextAreaLayout.setVerticalGroup(
            MTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MTextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout MessagePanelLayout = new javax.swing.GroupLayout(MessagePanel);
        MessagePanel.setLayout(MessagePanelLayout);
        MessagePanelLayout.setHorizontalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MOperatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MessagePanelLayout.setVerticalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MessagePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MOperatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Messages", MessagePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        month = monthArray[monthChoiceBox.getSelectedIndex()];
        
        if (!dayTxtField.getText().equals("")) {
            day = Integer.parseInt(dayTxtField.getText());
        } else {
            day = 0;
        }
        
        if (!yearTxtField.getText().equals("")) {
            year = Integer.parseInt(yearTxtField.getText());
        } else {
            year = 0;
        }
        
        
       
       
       
       message[] messageArray = fileDropFrame.getMessages();
       
       messageArray = parser.search(messageArray, day, month, year, senderTxtField.getText(), wordPhraseTxtField.getText());
       
        for (int i = 0; i < messageArray.length; i++)
        {
            
            //Append the stuff
            textArea1.append(Integer.toString(messageArray[i].day));
            textArea1.append((" " + messageArray[i].month));
            textArea1.append((" " + Integer.toString(messageArray[i].year)));
            textArea1.append((" " + messageArray[i].time));
            textArea1.append((" \n" + messageArray[i].sender));
            textArea1.append((" \n" + messageArray[i].content));
            textArea1.append("\n");
            textArea1.append("\n");
            
        }
       
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void yearTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTxtFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fileDropFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalProjectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalProjectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalProjectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalProjectUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalProjectUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MOperatePanel;
    private javax.swing.JPanel MTextArea;
    private javax.swing.JPanel MessagePanel;
    private javax.swing.JTextField dayTxtField;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox monthChoiceBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField senderTxtField;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextField wordPhraseTxtField;
    private javax.swing.JTextField yearTxtField;
    // End of variables declaration//GEN-END:variables
}
